apiVersion: v1
kind: ConfigMap
metadata:
  name: sinria-bridge-config
  namespace: "{{ .Release.Namespace }}"
data:
  SINRIA_BRIDGE_APP_ID: "{{ .Values.bridge.appId }}"
  SINRIA_BRIDGE_TENANT_ID: "{{ .Values.bridge.tenantId }}"
  SINRIA_BRIDGE_TRANSPORT: "{{ .Values.bridge.transport }}"
  SINRIA_BRIDGE_POLL_INTERVAL_SECONDS: "{{ .Values.bridge.pollIntervalSeconds }}"
