apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: sinria-bridge
      namespace: "{{ .Release.Namespace }}"
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: sinria-worker
      namespace: "{{ .Release.Namespace }}"
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: sinria-tool-executor
      namespace: "{{ .Release.Namespace }}"
