#!/usr/bin/env python3
"""ML training and fine-tuning helper tool for Sinria.

This tool deliberately keeps heavy training execution outside the tool handler:
it validates the environment, writes reproducible LoRA/SFT project scaffolds,
and returns explicit commands that the agent can run via the terminal/process
Tools. That keeps long-running GPU/CPU jobs observable and interruptible.
"""

from __future__ import annotations

import importlib.util
import json
import os
import platform
import shlex
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, Optional

from tools.registry import registry


_PACKAGE_IMPORTS = {
    "accelerate": "accelerate",
    "datasets": "datasets",
    "peft": "peft",
    "torch": "torch",
    "transformers": "transformers",
    "trl": "trl",
    "wandb": "wandb",
    # Optional/mostly CUDA. On Apple Silicon, bitsandbytes is often unavailable;
    # training can still use fp16/bf16/MPS without 4-bit quantization.
    "bitsandbytes": "bitsandbytes",
}

_DEFAULT_REQUIREMENTS = """accelerate>=0.34.0
datasets>=2.20.0
peft>=0.12.0
safetensors>=0.4.0
torch>=2.3.0
transformers>=4.44.0
trl>=0.10.0
wandb>=0.17.0
"""

_SAMPLE_DATASET = """{"text": "### Instruction:\nSinriaとは何ですか？\n\n### Response:\nSinriaは医療機関向けのAIエージェント基盤です。"}
{"text": "### Instruction:\n診療同意説明で重要なことは？\n\n### Response:\n患者の理解度、リスク、代替案、同意意思を確認し、記録することです。"}
"""

_TRAIN_SCRIPT = r'''#!/usr/bin/env python3
"""LoRA/QLoRA supervised fine-tuning entrypoint generated by Sinria."""

from __future__ import annotations

import argparse
import os
from pathlib import Path

import torch
from datasets import load_dataset
from peft import LoraConfig
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments
from trl import SFTTrainer


def _best_dtype():
    if torch.cuda.is_available():
        return torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    if getattr(torch.backends, "mps", None) and torch.backends.mps.is_available():
        return torch.float16
    return torch.float32


def main() -> None:
    parser = argparse.ArgumentParser(description="LoRA/QLoRA SFT training")
    parser.add_argument("--base-model", required=True)
    parser.add_argument("--dataset", required=True, help="JSONL/JSON/CSV path or Hugging Face dataset id")
    parser.add_argument("--text-field", default="text")
    parser.add_argument("--output-dir", default="./outputs/lora")
    parser.add_argument("--max-seq-length", type=int, default=2048)
    parser.add_argument("--max-steps", type=int, default=100)
    parser.add_argument("--epochs", type=float, default=None)
    parser.add_argument("--learning-rate", type=float, default=2e-4)
    parser.add_argument("--batch-size", type=int, default=1)
    parser.add_argument("--grad-accum", type=int, default=8)
    parser.add_argument("--lora-r", type=int, default=16)
    parser.add_argument("--lora-alpha", type=int, default=32)
    parser.add_argument("--lora-dropout", type=float, default=0.05)
    parser.add_argument("--report-to", default="none", choices=["none", "wandb"])
    parser.add_argument("--push-to-hub", action="store_true")
    parser.add_argument("--hub-model-id", default=None)
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if Path(args.dataset).exists():
        suffix = Path(args.dataset).suffix.lower()
        if suffix in {".jsonl", ".json"}:
            dataset = load_dataset("json", data_files=str(args.dataset), split="train")
        elif suffix == ".csv":
            dataset = load_dataset("csv", data_files=str(args.dataset), split="train")
        else:
            raise ValueError(f"Unsupported local dataset extension: {suffix}")
    else:
        dataset = load_dataset(args.dataset, split="train")

    tokenizer = AutoTokenizer.from_pretrained(args.base_model, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        args.base_model,
        torch_dtype=_best_dtype(),
        device_map="auto" if torch.cuda.is_available() else None,
    )

    peft_config = LoraConfig(
        r=args.lora_r,
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
        bias="none",
        task_type="CAUSAL_LM",
        target_modules="all-linear",
    )

    training_args = TrainingArguments(
        output_dir=str(output_dir),
        max_steps=args.max_steps if args.epochs is None else -1,
        num_train_epochs=args.epochs if args.epochs is not None else 1,
        per_device_train_batch_size=args.batch_size,
        gradient_accumulation_steps=args.grad_accum,
        learning_rate=args.learning_rate,
        logging_steps=5,
        save_steps=50,
        save_total_limit=3,
        bf16=torch.cuda.is_available() and torch.cuda.is_bf16_supported(),
        fp16=(torch.cuda.is_available() and not torch.cuda.is_bf16_supported()) or (
            getattr(torch.backends, "mps", None) and torch.backends.mps.is_available()
        ),
        report_to=[] if args.report_to == "none" else [args.report_to],
        push_to_hub=args.push_to_hub,
        hub_model_id=args.hub_model_id,
    )

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        dataset_text_field=args.text_field,
        max_seq_length=args.max_seq_length,
        peft_config=peft_config,
        args=training_args,
    )
    trainer.train()
    trainer.save_model(str(output_dir))
    tokenizer.save_pretrained(str(output_dir))
    if args.push_to_hub:
        trainer.push_to_hub()


if __name__ == "__main__":
    main()
'''

_README_TEMPLATE = """# Sinria ML Fine-tuning Project

This project was generated by Sinria's `ml_training` tool. It is a small,
reproducible LoRA/SFT workspace for local or server-side fine-tuning.

## Files

- `requirements.txt` — Python dependencies.
- `train_lora.py` — Hugging Face Transformers + TRL + PEFT training entrypoint.
- `data/sample.jsonl` — tiny JSONL example using a `text` field.
- `outputs/` — generated checkpoints/adapters.

## Install

```bash
python3 -m venv .venv
source .venv/bin/activate
python -m pip install --upgrade pip
python -m pip install -r requirements.txt
```

## Run smoke fine-tuning

```bash
python train_lora.py \
  --base-model {base_model} \
  --dataset data/sample.jsonl \
  --text-field {text_field} \
  --output-dir {output_dir} \
  --max-steps {max_steps} \
  --batch-size {batch_size} \
  --grad-accum {grad_accum} \
  --learning-rate {learning_rate}
```

## Optional integrations

- Hugging Face Hub upload: set `HF_TOKEN`, add `--push-to-hub --hub-model-id org/name`.
- W&B tracking: set `WANDB_API_KEY`, add `--report-to wandb`.

## Safety / privacy

Do not put patient-identifiable or confidential data in training sets unless the
storage, compute target, retention policy, and consent/legal basis are approved.
Keep datasets versioned and auditable.
"""


def _json(data: Dict[str, Any]) -> str:
    return json.dumps(data, ensure_ascii=False, indent=2)


def _package_available(import_name: str) -> bool:
    return importlib.util.find_spec(import_name) is not None


def _detect_torch() -> Dict[str, Any]:
    if not _package_available("torch"):
        return {"installed": False}
    try:
        import torch  # type: ignore

        return {
            "installed": True,
            "version": getattr(torch, "__version__", None),
            "cuda_available": bool(torch.cuda.is_available()),
            "cuda_device_count": int(torch.cuda.device_count()) if torch.cuda.is_available() else 0,
            "mps_available": bool(
                getattr(torch.backends, "mps", None) is not None
                and torch.backends.mps.is_available()
            ),
        }
    except Exception as exc:  # pragma: no cover - defensive environment probe
        return {"installed": True, "probe_error": str(exc)}


def _env_check() -> str:
    packages = {
        package: _package_available(import_name)
        for package, import_name in _PACKAGE_IMPORTS.items()
    }
    missing_core = [
        name for name in ["accelerate", "datasets", "peft", "torch", "transformers", "trl"]
        if not packages.get(name)
    ]
    result = {
        "success": True,
        "python": sys.version.split()[0],
        "platform": platform.platform(),
        "commands": {
            "git": bool(shutil.which("git")),
            "hf": bool(shutil.which("hf")),
            "wandb": bool(shutil.which("wandb")),
        },
        "packages": packages,
        "torch": _detect_torch(),
        "credentials": {
            "HF_TOKEN_set": bool(os.getenv("HF_TOKEN") or os.getenv("HUGGINGFACE_HUB_TOKEN")),
            "WANDB_API_KEY_set": bool(os.getenv("WANDB_API_KEY")),
        },
        "ready_for_local_lora": not missing_core,
        "missing_core_packages": missing_core,
        "install_command": "python -m pip install -U " + " ".join(_DEFAULT_REQUIREMENTS.split()),
        "notes": [
            "bitsandbytes is optional and mainly useful on CUDA GPUs; Apple Silicon can use MPS without it.",
            "Use terminal(background=true, notify_on_complete=true) for real training runs so progress remains observable.",
        ],
    }
    return _json(result)


def _safe_project_dir(project_dir: str) -> Path:
    if not project_dir or not project_dir.strip():
        raise ValueError("project_dir is required")
    path = Path(project_dir).expanduser()
    if not path.is_absolute():
        path = Path.cwd() / path
    return path.resolve()


def _write_file(path: Path, content: str, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError(f"Refusing to overwrite existing file: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _scaffold_lora(args: Dict[str, Any]) -> str:
    project_dir = _safe_project_dir(str(args.get("project_dir") or "ml-finetune"))
    overwrite = bool(args.get("overwrite", False))
    base_model = str(args.get("base_model") or "Qwen/Qwen2.5-0.5B-Instruct")
    text_field = str(args.get("text_field") or "text")
    output_dir = str(args.get("output_dir") or "outputs/lora")
    max_steps = int(args.get("max_steps") or 100)
    batch_size = int(args.get("batch_size") or 1)
    grad_accum = int(args.get("grad_accum") or 8)
    learning_rate = float(args.get("learning_rate") or 2e-4)

    if project_dir.exists() and any(project_dir.iterdir()) and not overwrite:
        raise FileExistsError(
            f"Project directory is not empty: {project_dir}. Set overwrite=true to replace generated files."
        )

    _write_file(project_dir / "requirements.txt", _DEFAULT_REQUIREMENTS, overwrite)
    _write_file(project_dir / "train_lora.py", _TRAIN_SCRIPT, overwrite)
    _write_file(project_dir / "data" / "sample.jsonl", _SAMPLE_DATASET, overwrite)
    _write_file(
        project_dir / "README.md",
        _README_TEMPLATE.format(
            base_model=base_model,
            text_field=text_field,
            output_dir=output_dir,
            max_steps=max_steps,
            batch_size=batch_size,
            grad_accum=grad_accum,
            learning_rate=learning_rate,
        ),
        overwrite,
    )

    project_dir_arg = shlex.quote(str(project_dir))
    base_model_arg = shlex.quote(base_model)
    text_field_arg = shlex.quote(text_field)
    output_dir_arg = shlex.quote(output_dir)
    max_steps_arg = shlex.quote(str(max_steps))
    batch_size_arg = shlex.quote(str(batch_size))
    grad_accum_arg = shlex.quote(str(grad_accum))
    learning_rate_arg = shlex.quote(str(learning_rate))

    run_command = (
        f"cd {project_dir_arg} && "
        "python train_lora.py "
        f"--base-model {base_model_arg} "
        "--dataset data/sample.jsonl "
        f"--text-field {text_field_arg} "
        f"--output-dir {output_dir_arg} "
        f"--max-steps {max_steps_arg} "
        f"--batch-size {batch_size_arg} "
        f"--grad-accum {grad_accum_arg} "
        f"--learning-rate {learning_rate_arg}"
    )
    install_command = (
        f"cd {project_dir_arg} && python3 -m venv .venv && "
        "source .venv/bin/activate && python -m pip install --upgrade pip && "
        "python -m pip install -r requirements.txt"
    )
    return _json(
        {
            "success": True,
            "project_dir": str(project_dir),
            "files": [
                "requirements.txt",
                "train_lora.py",
                "data/sample.jsonl",
                "README.md",
            ],
            "install_command": install_command,
            "run_command": run_command,
            "recommended_terminal_usage": {
                "install": "terminal(command=install_command, timeout=600)",
                "train": "terminal(command='source .venv/bin/activate && ...', background=true, notify_on_complete=true)",
            },
        }
    )


def _validate_dataset(dataset_path: str, text_field: str = "text", max_rows: int = 5) -> str:
    if not dataset_path:
        raise ValueError("dataset_path is required")
    path = Path(dataset_path).expanduser()
    if not path.exists():
        raise FileNotFoundError(f"Dataset path not found: {path}")
    rows = []
    if path.suffix.lower() in {".jsonl", ".json"}:
        with path.open("r", encoding="utf-8") as fh:
            for idx, line in enumerate(fh, start=1):
                if not line.strip():
                    continue
                obj = json.loads(line)
                rows.append({"line": idx, "has_text_field": text_field in obj, "keys": sorted(obj.keys())})
                if len(rows) >= max_rows:
                    break
    else:
        return _json({"success": False, "error": f"Unsupported validation extension: {path.suffix}"})
    return _json(
        {
            "success": True,
            "dataset_path": str(path.resolve()),
            "text_field": text_field,
            "sampled_rows": rows,
            "valid": bool(rows) and all(row["has_text_field"] for row in rows),
        }
    )


def _plan(args: Dict[str, Any]) -> str:
    base_model = str(args.get("base_model") or "Qwen/Qwen2.5-0.5B-Instruct")
    return _json(
        {
            "success": True,
            "recommended_flow": [
                "Run action='env_check' to inspect packages, GPU/MPS/CUDA, and credentials.",
                "Run action='scaffold_lora' to create a reproducible LoRA fine-tuning workspace.",
                "Replace data/sample.jsonl with a reviewed dataset. For medical/confidential data, confirm approved storage and compute first.",
                "Install dependencies in the generated venv.",
                "Launch training with terminal(background=true, notify_on_complete=true), then monitor via process.poll/log.",
                "Optionally upload adapters to Hugging Face Hub only after privacy and licensing checks.",
            ],
            "base_model": base_model,
            "local_compute_notes": [
                "Small smoke tests can run on CPU/MPS; practical LLM fine-tuning usually needs a CUDA GPU or remote runner.",
                "Use LoRA adapters first; full fine-tuning is much more expensive and riskier.",
            ],
        }
    )


def ml_training(action: str, **kwargs: Any) -> str:
    """Dispatch ML training helper actions."""
    try:
        action = (action or "env_check").strip().lower()
        if action == "env_check":
            return _env_check()
        if action == "plan":
            return _plan(kwargs)
        if action == "scaffold_lora":
            return _scaffold_lora(kwargs)
        if action == "validate_dataset":
            return _validate_dataset(
                dataset_path=str(kwargs.get("dataset_path") or ""),
                text_field=str(kwargs.get("text_field") or "text"),
                max_rows=int(kwargs.get("max_rows") or 5),
            )
        return _json({"success": False, "error": f"Unknown action: {action}"})
    except Exception as exc:
        return _json({"success": False, "error": str(exc), "action": action})


ML_TRAINING_SCHEMA = {
    "name": "ml_training",
    "description": (
        "Prepare and validate local/remote ML training or LLM fine-tuning workflows. "
        "Can inspect dependencies, scaffold a Hugging Face Transformers/TRL/PEFT LoRA project, "
        "validate JSONL datasets, and return explicit install/run commands. Does not silently launch "
        "long training jobs; use terminal/process for observable execution."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "action": {
                "type": "string",
                "enum": ["env_check", "plan", "scaffold_lora", "validate_dataset"],
                "description": "Operation to perform.",
            },
            "project_dir": {"type": "string", "description": "Directory for scaffold_lora output."},
            "base_model": {"type": "string", "description": "HF model id for LoRA fine-tuning."},
            "dataset_path": {"type": "string", "description": "Local JSONL/JSON dataset path for validation."},
            "text_field": {"type": "string", "description": "Dataset text column/field name. Default: text."},
            "output_dir": {"type": "string", "description": "Training output directory inside the project."},
            "max_steps": {"type": "integer", "description": "Smoke/default training max steps."},
            "batch_size": {"type": "integer", "description": "Per-device training batch size."},
            "grad_accum": {"type": "integer", "description": "Gradient accumulation steps."},
            "learning_rate": {"type": "number", "description": "Fine-tuning learning rate."},
            "overwrite": {"type": "boolean", "description": "Allow overwriting generated scaffold files."},
            "max_rows": {"type": "integer", "description": "Rows to sample for dataset validation."},
        },
        "required": ["action"],
    },
}


registry.register(
    name="ml_training",
    toolset="ml_training",
    schema=ML_TRAINING_SCHEMA,
    handler=lambda args, **kw: ml_training(**args),
    check_fn=lambda: True,
    emoji="🏋️",
)
